config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'copiers#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

  root 'home#index'
  resources :copiers
  resources :devices

end

app/models/copier.rb
class Copier < ActiveRecord::Base
  mount_uploader :image, CopierUploader

  attr_accessible :nazwa, :stan, :cena, :promocja, :funkcjonalnosc_st, :funkcjonalnosc_op, :predkosc_drukowania, :duplex,
                  :formaty_oryginalow, :podajnik_papieru_st, :gramatura_papieru, :rozdzielczosc_drukowania, :rozdzielczosc_kopiowania,
                  :tryb_skanowania, :drukowanie_sieciowe, :podajnik_oryginalow_st, :dysk_hdd, :druk_nosniki_danych, :czas_nagrzewania,
                  :image

  validates :nazwa, presence: { message: "Wprowadź nazwę kserokopiarki." }
  validates :cena, presence: { message: "Wprowadź cenę kserokopiarki." }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/copiers_controller.rb
class CopiersController < ApplicationController

  def index
    @copiers = Copier.all
  end

  def new
    @copier = Copier.new
  end

  def create
    @copier = Copier.new(params[:copier])
    if @copier.save
      redirect_to copiers_path, notice: "Kserokopiarka została dodana."
    else
      render "new"
    end
  end

  def edit
    @copier = Copier.find(params[:id])
  end

  def update
    @copier = Copier.find(params[:id])
    if @copier.update_attributes(params[:copier])
      redirect_to copiers_path, notice: "Kserokoparka została zaktualizowana."
    else
      render "edit"
    end
  end

  def destroy
    @copier = Copier.find(params[:id])
    @copier.destroy!
    redirect_to copiers_path, notice: "Kserokopiarka została usunięta."
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to dashboard_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/copiers_helper.rb
module CopiersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/copiers/_form.html.erb
<div class="form-header text-center">
  <% if params[:action] == "new" %>
    <h3>Dodaj kserokopiarkę</h3>
  <% elsif params[:action] == "edit" %>
    <h3>Edytuj kserokopiarkę</h3>
  <% end %>
</div>

<div class="row">
  <%= form_for @copier, html: { multipart: true } do |f| %>
    <div class="col-xs-12 col-md-6 copiers-form">

      <div class="form-group">
        <%= f.label :nazwa %>
        <%= f.text_field :nazwa, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :stan, class: "form-checkbox" %>
        <%= f.select :stan, ['nowa', 'używana'], class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :cena %>
        <%= f.text_field :cena, class: "form-control" %>
      </div>
      <div class="form-group form-inline">
        <%= f.check_box :promocja, class: "form-checkbox" %>
        <%= f.label :promocja %>
      </div>
      <div class="form-group">
        <%= f.label :funkcjonalnosc_st, "Funkcjonalność w standardzie" %>
        <%= f.text_field :funkcjonalnosc_st, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :funkcjonalnosc_op, "Funkcjonalność opcjonalna" %>
        <%= f.text_field :funkcjonalnosc_op, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :predkosc_drukowania, "Prędkość drukowania A4" %>
        <%= f.text_field :predkosc_drukowania, class: "form-control" %>
      </div>
      <div class="form-group form-inline">
        <%= f.check_box :duplex, class: "form-checkbox" %>
        <%= f.label :duplex, "Drukowanie dwustronne (duplex)" %>
      </div>
      <div class="form-group">
        <%= f.label :formaty_oryginalow, "Formaty oryginałów" %>
        <%= f.text_field :formaty_oryginalow, class: "form-control" %>
      </div>
    </div>

    <div class="col-xs-12 col-md-6 copiers-form">
      <div class="form-group">
        <%= f.label :podajnik_papieru_st, "Podajniki papieru w standardzie" %>
        <%= f.text_field :podajnik_papieru_st, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :gramatura_papieru, "Gramatura papieru" %>
        <%= f.text_field :gramatura_papieru, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :rozdzielczosc_drukowania, "Rozdzielczość drukowania" %>
        <%= f.text_field :rozdzielczosc_drukowania, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :rozdzielczosc_kopiowania, "Rozdzielczość kopiowania" %>
        <%= f.text_field :rozdzielczosc_kopiowania, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :tryb_skanowania, "Tryby skanowania" %>
        <%= f.text_field :tryb_skanowania, class: "form-control" %>
      </div>
      <div class="form-group form-inline">
        <%= f.check_box :drukowanie_sieciowe, class: "form-checkbox" %>
        <%= f.label :drukowanie_sieciowe %>
      </div>
      <div class="form-group form-inline">
        <%= f.check_box :podajnik_oryginalow_st, class: "form-checkbox" %>
        <%= f.label :podajnik_oryginalow_st, "Podajnik oryginałów w standardzie" %>
      </div>
      <div class="form-group form-inline">
        <%= f.check_box :dysk_hdd, class: "form-checkbox" %>
        <%= f.label :dysk_hdd %>
      </div>
      <div class="form-group form-inline">
        <%= f.check_box :druk_nosniki_danych, class: "form-checkbox" %>
        <%= f.label :druk_nosniki_danych, "Druk z nośników danych" %>
      </div>
      <div class="form-group">
        <%= f.label :czas_nagrzewania %>
        <%= f.text_field :czas_nagrzewania, class: "form-control" %>
      </div>
    </div>

    <div class="form-upload">
      <%= f.label :image, "Załącz zdjęcie" %>
      <%= f.file_field :image %>
    </div>

    <div class="text-center">
      <%= f.submit "Wprowadź", class: "btn btn-primary action" %>
    </div>

  <% end %>
</div>

app/views/copiers/_validation.html.erb
<div class="row center">
  <div class="col-md-6 col-xs-10 center">
    <% if @copier.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @copier.errors.messages.values.each do |message| %>
            <% message.each do |msg| %>
              <li class="alert-item">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Błąd:</span>
                <%= msg %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/copiers/edit.html.erb
<%= render "copiers/validation" %>
<%= render "copiers/form" %>

app/views/copiers/index.html.erb
<% @copiers.each do |copier| %>
  <div class="row copier">

    <div class="col-xs-12 col-md-5">
      <div class="panel-left text-center">
        <div class="panel-left-header">
          <h4><% if copier.promocja? %>PROMOCJA!!!<% end %></h4>
        </div>
        <div class="panel-left-body">
          <%= image_tag copier.image.thumb.url if copier.image? %>
        </div>
        <div class="panel-left-footer">
          <h4>Cena: <%= copier.cena %> zł</h4>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-7">
      <div class="panel-right">
        <div class="panel-right-header text-center">
          <h4><%= copier.nazwa %></h4>
        </div>
        <div class="panel-right-body">
          <table class="table table-striped">
            <tr>
              <th>Stan</th>
              <td><%= copier.stan %></td>
            </tr>
            <tr>
              <th>Funkcjonalność w standardzie</th>
              <td><%= copier.funkcjonalnosc_st %></td>
            </tr>
            <tr>
              <th>Funkcjonalność opcjonalna</th>
              <td><%= copier.funkcjonalnosc_op %></td>
            </tr>
            <tr>
              <th>Prędkość drukowania A4</th>
              <td><%= copier.predkosc_drukowania %> stron/minutę</td>
            </tr>
            <tr>
              <th>Drukowanie dwustronne (duplex)</th>
              <td><% if copier.duplex? %>tak<% else %>nie<% end %></td>
            </tr>
            <tr>
              <th>Formaty oryginałów</th>
              <td><%= copier.formaty_oryginalow %></td>
            </tr>
          </table>
          <div id="<%= copier.id.to_s %>" class="panel-collapse collapse">
            <table class="table table-striped">
              <tr>
                <th>Podajniki papieru w standardzie</th>
                <td><%= copier.podajnik_papieru_st %></td>
              </tr>
              <tr>
                <th>Gramatura papieru</th>
                <td><%= copier.gramatura_papieru %> g/m<sup>2</sup></td>
              </tr>
              <tr>
                <th>Rozdzielczość drukowania</th>
                <td><%= copier.rozdzielczosc_drukowania %> dpi</td>
              </tr>
              <tr>
                <th>Rozdzielczość kopiowania</th>
                <td><%= copier.rozdzielczosc_kopiowania %> dpi</td>
              </tr>
              <tr>
                <th>Tryby skanowania</th>
                <td><%= copier.tryb_skanowania %></td>
              </tr>
              <tr>
                <th>Drukowanie sieciowe</th>
                <td><% if copier.drukowanie_sieciowe? %>tak<% else %>nie<% end %></td>
              </tr>
              <tr>
                <th>Podajnik oryginałów w standardzie</th>
                <td><% if copier.podajnik_oryginalow_st? %>tak<% else %>nie<% end %></td>
              </tr>
              <tr>
                <th>Dysk HDD</th>
                <td><% if copier.dysk_hdd? %>tak<% else %>nie<% end %></td>
              </tr>
              <tr>
                <th>Druk z nośników danych</th>
                <td><% if copier.druk_nosniki_danych? %>tak<% else %>nie<% end %></td>
              </tr>
              <tr>
                <th>Czas nagrzewania</th>
                <td><%= copier.czas_nagrzewania %> sekund</td>
              </tr>
            </table>
          </div>
        </div>
        <div class="panel-right-footer">
          <ul class="list">
            <li><%= link_to "Więcej", "#" + copier.id.to_s, class: "btn btn-info", data: { toggle: "collapse", target: "#" + copier.id.to_s } %></li>
          </ul>
          <% if user_signed_in? %>
            <ul class="list pull-right">
              <li><%= link_to "Edytuj", edit_copier_path(copier), class: "btn btn-warning", method: :get %></li>
              <li><%= link_to "Usuń", copier, method: :delete, data:{ confirm: "Czy na pewno chcesz usunąć kserokopiarkę?"}, class: "btn btn-danger", method: :get %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/copiers/new.html.erb
<%= render "copiers/validation" %>
<%= render "copiers/form" %>

app/views/devices/index.html.erb
<h1>Urządzenia biurowe</h1>

app/views/home/_about_us.html.erb
<section id="about_us">
  <a name="about"></a>

  <div class="row">
    <div class="col-sm-12 text-center welcome">
      <h2>Serdecznie witamy w serwisie internetowym firmy <b>Abart</b>.</h2>
      <h3>Dlaczego to właśnie my powinniśmy zadbać o Twój sprzętem biurowym:</h3>
    </div>
  </div>

  <div class="panels-wrapper">
    <div class="row">

      <div class="col-sm-4 panel-item">
        <div class="panel">
          <div class="panel-header">
            <%= image_tag("images/klient.png", :class => "img-responsive") %>
          </div>
          <div class="panel-body text-center">
            <h3>Dbałość o klienta</h3>
            <p>Nasi stali klienci cenią sobie szybkość i solidność, dlatego oferujemy najkrótszy na rynku czas reakcji oraz gwarantujemy satysfakcję ze współpracy.</p>
          </div>
        </div>
      </div>

      <div class="col-sm-4 panel-item">
        <div class="panel">
          <div class="panel-header">
            <%= image_tag("images/oferta.png", :class => "img-responsive") %>
          </div>
          <div class="panel-body text-center">
            <h3>Atrakcyjne oferty</h3>
            <p>Naszym klientom gwarantujemy najniższe ceny sprzętu oraz najwyższy poziom usług. Zawsze oferujemy najkorzystniejsze warunki zakupu.</p>
          </div>
        </div>
      </div>

      <div class="col-sm-4 panel-item">
        <div class="panel">
          <div class="panel-header">
            <%= image_tag("images/jakosc.png", :class => "img-responsive") %>
          </div>
          <div class="panel-body text-center">
            <h3>Jakość</h3>
            <p>Dajemy gwarancję na sprzęt używany oraz zapewniamy, że jest on sprawdzony i najwyższej jakości, tak samo jak poziom naszych usług.</p>
          </div>
        </div>
      </div>

    </div>
    <div class="row">

      <div class="col-sm-4 panel-item">
        <div class="panel">
          <div class="panel-header">
            <%= image_tag("images/wiedza.png", :class => "img-responsive") %>
          </div>
          <div class="panel-body text-center">
            <h3>Wiedza i doświadczenie</h3>
            <p>Posiadajamy 10 letnie doświadczenie oraz niezbędną wiedzę w serwisowaniu urządzeń biurowych.</p>
          </div>
        </div>
      </div>

      <div class="col-sm-4 panel-item">
        <div class="panel">
          <div class="panel-header">
            <%= image_tag("images/pasja.png", :class => "img-responsive") %>
          </div>
          <div class="panel-body text-center">
            <h3>Pasja</h3>
            <p>To czym się zajmujemy jest nie tylko naszą pracą, ale przede wszystkim pasją. Poświęciliśmy wiele lat życia by robić to, co prawdziwie kochamy.</p>
          </div>
        </div>
      </div>

      <div class="col-sm-4 panel-item">
        <div class="panel">
          <div class="panel-header">
            <%= image_tag("images/wyzwanie.png", :class => "img-responsive") %>
          </div>
          <div class="panel-body text-center">
            <h3>Wyzwania</h3>
            <p>Podejmujemy się najbardziej skomplikowanych napraw, nawet jeśli inny serwis nie był w stanie rozwiązać problemu.</p>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/home/_copiers.html.erb
<section class="devices">
  <div class="row">
    <a name="copiers"></a>
    <div class="col-sm-12">

      <div class="page-header">
        <h2 class="background"><span>KSEROKOPIARKI</span></h2>
      </div>
      <div class="row">

        <div class="col-sm-6 text-center"><%= image_tag("images/copier.jpg") %></div>

        <div class="col-sm-6">
          <h3>Nasza oferta</h3>
          <p>Posiadamy kserokopiarki nowe, powystawowe i używane. Na używane dajemy gwarację oraz
            zapewaniamy, że jest to sprzęt sprawdzony i najwyższej jakości. Oferujemy kserokopiarki
            używane ze względu na bardzo atrakcyjną cenę w porównaniu do nowego sprzętu przy zachowaniu
            jednakowej użyteczności oraz jakości nowych maszyn.</p>
          <%= button_to "Sprawdź", copiers_path, class: "btn btn-success center-block", method: :get %>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/home/_other_devices.html.erb
<section id="other_devices" class="devices">
  <div class="row">
    <a name="other_devices"></a>
    <div class="col-sm-12">

      <div class="page-header">
        <h2 class="background"><span>INNE URZĄDZENIA</span></h2>
      </div>
      <div class="row">

        <div class="col-sm-6 space">
          <h3>Nasza oferta</h3>
          <p>Oprócz kserokopiarek nasza firma oferuje także:</p>
          <ul>
            <li>drukarki</li>
            <li>faksy</li>
            <li>urządzenia wielofunkcyjne</li>
            <li>oraz niszczarki</li>
          </ul>
          <button type="button" class="btn btn-success center-block">Sprawdź oferte</button>
        </div>

        <div class="col-sm-6 text-center"><%= image_tag("images/fax.jpg") %></div>

      </div>
    </div>
  </div>
</section>

app/views/home/_service.html.erb
<section id="service" class="devices">
  <div class="row">
    <a name="service"></a>
    <div class="col-sm-12">

      <div class="page-header">
        <h2 class="background"><span>SERWIS</span></h2>
      </div>
      <div class="row">

        <div class="col-sm-6 text-center">
          <%= image_tag("images/service.jpg") %>
          <h5>Nasz serwis zapewnia satysfakcję z dokonanego wyboru</h5>
        </div>

        <div class="col-sm-6">
          <h3>Nasza oferta</h3>
          <p>Oferujemy serwis gwarancyjny oraz pogwarancyjny wszystkich typów kserokopiarek
            oraz drukarek laserowych. Nasza firma posiada wieloletnie doświadczenie w naprawach
            urządzeń kopiujących. podejmujemy się najbardziej skomplikowanych napraw, nawet
            jeżeli inny serwis nie był w stanie rozwiązać problemu. Nasi stali klienci cenią
            szybkość i solidność naszego serwisu. Proponujemy niestandardowe opcje serwisowania
            jak kontrakty ze zryczałtowaną opłatą miesięczną. Dojeżdżamy bezpłatnie na terenie
            Zabrza i okolic.</p>
            <h4>Gwarantujemy:</h4>
            <ul>
              <li>fachową pomoc i utrzymanie sprawności urządzeń biurowych</li>
              <li>urządzenie zastępcze w przypadku dłuższej naprawy</li>
              <li>stałą dostępność części zamiennych i materiałów eksploatacyjnych</li>
              <li>szybką i skuteczną reakcję na zgłaszane problemy techniczne</li>
              <li>stałą konserwację urządzeń zmniejszającą możliwość wystąpienia nieoczekiwanych awarii</li>
              <li>bezpłatne uruchomienie, transport, przeszkolenie, oraz dogodne warunki gwarancji</li>
              <li>konfiguracje urządzeń pracujących w sieci.</li>
            </ul>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/home/_toners.html.erb
<section id="toners" class="devices">
  <div class="row">
    <a name="toners"></a>
    <div class="col-sm-12">

      <div class="page-header">
        <h2 class="background"><span>TONERY I TUSZE</span></h2>
      </div>

      <div class="row">
        <div class="col-sm-6 space">
          <h3>Nasza oferta</h3>
          <p>Posiadamy tonery do każdego modelu kserokopiarki i drukarki laserowej, a także tusze do drukarek atramentowych.</p>
        </div>
        <div class="col-sm-6 text-center"><%= image_tag("images/toner.jpg") %></div>
      </div>

      <div class="row">
        <div class="col-sm-6 text-center">
          <%= image_tag("images/toner1.jpg") %>
          <h5>Regeneracja już od 50 zł !!!</h5>
        </div>
        <div class="col-sm-6 space">
          <h3>Regeneracja Tonerów</h3>
          <p>Regenerujemy tonery do drukarek, kserokopiarek i faxów laserowych. Dzięki regeneracji toneru zyskujesz nawet do 70%
          oszczędności, dodatkowo chronisz środowisko naturalne, gdyż twój zużyty cartridge jest wykorzystywany kilka razy.
          Często tonery regenerowane wystarczają na większą ilość wydruków niż tonery oryginalne.</p>
          <p>Regeneracja tonera nie polega tylko na uzupełnieniu proszku. Samo uzupełnienie proszku nie gwarantuje poprawnego
          działania cartridgea ani nie zapewnia dobrej jakości wydruku. Do regeneracji używamy tylko materiałów dobrej
          jakości i osobiście sprawdzonych przez nas.</p>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render "home/about_us" %>
<%= render "home/copiers" %>
<%= render "home/other_devices" %>
<%= render "home/service" %>
<%= render "home/toners" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/navbar" %>
  <%= render "shared/content" %>
  <% unless user_signed_in? %>
    <%= render "shared/footer" %>
  <% end %>
</body>
</html>

app/views/shared/_content.html.erb
<div class="container"><%= yield %></div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <section class="footer-main">
    <div class="container">
      <div class="row">
        <a name="contact"></a>

        <div class="col-md-3 col-sm-6 text-center">
          <div class="icon-box">
            <div class="icon"><%= image_tag("icons/telephone") %></div>
            <div class="content">(032) 726 21 43</div>
          </div>
        </div>

        <div class="col-md-3 col-sm-6 text-center">
          <div class="icon-box">
            <div class="icon"><%= image_tag("icons/mobile.png") %></div>
            <div class="content">+48 791 509 109</div>
            <div class="content">+48 601 159 412</div>
            <div class="content">+48 668 826 263</div>
            <div class="content">+48 501 524 788</div>
          </div>
        </div>

        <div class="col-md-3 col-sm-6 text-center">
          <div class="icon-box">
            <div class="icon"><%= image_tag("icons/mail") %></div>
            <div class="content">biuro@abart.net.pl</div>
          </div>
        </div>

        <div class="col-md-3 col-sm-6 text-center">
          <div class="icon-box">
            <div class="icon"><%= image_tag("icons/info") %></div>
            <div class="content">
              <p>abart s.c.</p>
              <p>41-806 Zabrze</p>
              <p>NIP 648-262-11-45</p>
              <p>Regon 240616117</p>
              <p>ING 76105015881000002316109251</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>

  <section class="footer-copyright">
    <div class="container">
      <div class="row">
        <p>2015 | Abart.pl © Dziękujemy za wizytę!
      <div>
    </div>
  </section>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Abart", root_path, class: "navbar-brand" %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: { toggle: "dropdown"} do %>
              Kserokopiarki <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to "Wprowadzone", copiers_path %></li>
              <li><%= link_to "Dodaj", new_copier_path %></li>
            </ul>
          </li>
          <li><%= link_to "Inne urządzenia", devices_path %></li>
          <li><%= link_to "Wyloguj", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% elsif controller.controller_name == "home" %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "O nas", "#about" %></li>
          <li><%= link_to "Kserokopiarki", "#copiers" %></li>
          <li><%= link_to "Inne urządzenia", "#other_devices" %></li>
          <li><%= link_to "Serwis", "#service" %></li>
          <li><%= link_to "Tonery i tusze", "#toners" %></li>
          <li><%= link_to "Kontakt", "#contact" %></li>
       </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right"><li></li></ul>
      <% end %>
    </div>

  </div>
</nav>